export const REQUEST_LOAD_CATEGORIES = 'REQUEST_LOAD_CATEGORIES';
export const RECEIVE_LOAD_CATEGORIES = 'RECEIVE_LOAD_CATEGORIES';
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const REQUEST_LOAD_DIRECTORS = 'REQUEST_LOAD_DIRECTORS';
export const RECEIVE_LOAD_DIRECTORS = 'RECEIVE_LOAD_DIRECTORS';