export const REQUEST_LOAD_COMPANIES = 'REQUEST_LOAD_COMPANIES';
export const RECEIVE_LOAD_COMPANIES = 'RECEIVE_LOAD_COMPANIES';
export const GET_COMPANY = 'GET_COMPANY';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';

export const REQUEST_LOAD_CATEGORIES = 'REQUEST_LOAD_CATEGORIES';
export const RECEIVE_LOAD_CATEGORIES = 'RECEIVE_LOAD_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const REQUEST_LOAD_DIRECTORS = 'REQUEST_LOAD_DIRECTORS';
export const RECEIVE_LOAD_DIRECTORS = 'RECEIVE_LOAD_DIRECTORS';